# 学校英文简称
school = "whpu"

# 使用学校地址签到
[[users]]
username = "用户名"
password = "密码"
alias = "简称"
addr = ""

# 使用随机地址在家签到
[[users]]
username = "用户名"
password = "密码"
alias = "简称"
addr = "home"

# 使用自定义地址在家签到
[[users]]
username = "用户名"
password = "密码"
alias = "简称"
addr = ["经度", "纬度", "实际地址"]
